services:
  - type: web
    name: matrix-lms-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: MatrixBackendAlphaVersion
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
